#this shows how to configure the sensors

configurations: [
  {               #cycle 0
    '0': [0,2,3,4],     #channel 0 is pinging; 0,3,4 are listening and any received echo is an indirect measurement in relation to 0
    '5': [5,1]          #channel 5 is pinging; 1,5 are listening and any received echo is an indirect measurement in relation to 5
  },
  {               #cycle 1
    '2': [2],          #channel 2 is pinging; only a direct measurement
    '3': [3]          #channel 3 is pinging; only a direct measurement
  }
]
